### ISSUE TITLE
Random File Always Created

### ISSUE THREAD

**Issue by PateeerQ** [SimoSbara/samp-chatbot#1]
im using Gemini AI 1.5-flash, every AI Prompt sended, Random Binary File always created.

![image](https://github.com/user-attachments/assets/411735d1-77ca-42c4-a57f-8da217c6a6cc)

**Comment by SimoSbara** [comment]
Hello, as I said to you on discord, this plugin doesn't do any file stream writing and I can't replicate the same behaviour.
Can you list all the plugins you are using and some pawn code if possibile? Thanks
