### ISSUE TITLE
Missing dependencies for Linux Server

### ISSUE THREAD

**Issue by riot6416** [SimoSbara/samp-chatbot#2]
Server_log:
```txt
[06/12/2024 13:38:04]  Loading plugin: samp-chatbot.so
[06/12/2024 13:38:04]   Failed (/lib32/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by plugins/samp-chatbot.so))

```

Where I can find this to be put into the server?
" /lib32/libstdc++.so.6: version `GLIBCXX_3.4.29' "

Note: I'm using Windows 10 OS, only the Server GCP is using Linux server. I Have no idea about Linux OS stuffs.

**Comment by SimoSbara** [comment]
Hello, which Linux Distro are you using? Ubuntu?

It seems that you are missing some dependencies of C++, try to do:
`sudo apt-get update` and `sudo apt-get install libstdc++6`

Let me know if it works.
